// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"app/infrastructure/db"
	"app/infrastructure/repository"
	"app/infrastructure/security"
	"app/internal/application/usecase/user"
)

// Injectors from wire.go:

func InitializeApp() *App {
	gormDB := db.NewConnection()
	userRepository := repository.NewUserRepository(gormDB)
	bcryptPasswordHasher := security.NewBcryptPasswordHasher()
	createUserUsecase := user.NewCreateUserUsecase(userRepository, bcryptPasswordHasher)
	app := &App{
		CreateUserUseCase: createUserUsecase,
	}
	return app
}

// wire.go:

type App struct {
	CreateUserUseCase *user.CreateUserUsecase
}
